services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    # para saber quais variáveis de ambiente podemos criar
    # devemos ir na documentação da imagem que estamos baixando la do Docker Hub.
    environment: 
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=blablabla
    expose:
      - 3306
      - 33060
  wordpress:
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=blablabla
      - WORDPRESS_DB_NAME=wordpress
volumes: 
  db_data:
  wp_data: